FROM golang:1.25-alpine

RUN apk add --no-cache git postgresql-client

RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x ./scripts/dev-entrypoint.sh

EXPOSE 8080
CMD ["./scripts/dev-entrypoint.sh"]
