import { Client } from "./stageConfig";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "p1",
    name: "محمد الأحمد",
    company: "شركة الرياض للتطوير العقاري",
    phone: "+966 50 123 4567",
    email: "mohammed.ahmed@riyadhdev.sa",
    value: 850000,
    stage: "deal",
    assignee: "سارة محمد",
    status: "hot",
    notes: "عميل مميز، تمت الموافقة على التمويل. ينتظر توقيع العقد النهائي.",
    updatedAt: "2026-03-05",
  },
  {
    id: "p2",
    name: "فاطمة العمري",
    company: "مجموعة العمري للمقاولات",
    phone: "+966 55 234 5678",
    email: "fatima@omari-group.sa",
    value: 320000,
    stage: "interested",
    assignee: "خالد السعدي",
    status: "warm",
    notes: "تطلب مزيداً من المعلومات عن برنامج المرابحة.",
    updatedAt: "2026-03-06",
  },
  {
    id: "p3",
    name: "عبدالله التميمي",
    company: "التميمي للتجارة والاستيراد",
    phone: "+966 54 345 6789",
    email: "a.tamimi@tamimi-trade.com",
    value: 500000,
    stage: "lead",
    assignee: "نورة الزهراني",
    status: "warm",
    notes: "تم التواصل الأولي. يحتاج عرضاً تفصيلياً للمنتج.",
    updatedAt: "2026-03-04",
  },
  {
    id: "p4",
    name: "هند الشمري",
    company: "الشمري للخدمات اللوجستية",
    phone: "+966 56 456 7890",
    email: "hind@shamri-logistics.sa",
    value: 175000,
    stage: "new",
    assignee: "أحمد العتيبي",
    status: "cold",
    notes: "",
    updatedAt: "2026-03-07",
  },
  {
    id: "p5",
    name: "سلطان القحطاني",
    company: "القحطاني للمشاريع الصناعية",
    phone: "+966 50 567 8901",
    email: "sultan@qahtani-ind.sa",
    value: 1200000,
    stage: "deal",
    assignee: "سارة محمد",
    status: "hot",
    notes: "صفقة كبيرة، تم اعتمادها من اللجنة. قيد التنفيذ.",
    updatedAt: "2026-03-03",
  },
  {
    id: "p6",
    name: "رنا الدوسري",
    company: "الدوسري للتكنولوجيا والحلول الرقمية",
    phone: "+966 55 678 9012",
    email: "rana@dosari-tech.sa",
    value: 95000,
    stage: "reject",
    assignee: "خالد السعدي",
    status: "cold",
    notes: "لم تستوفِ معايير التأهيل الائتماني للفترة الحالية.",
    updatedAt: "2026-02-28",
  },
  {
    id: "p7",
    name: "يوسف الغامدي",
    company: "مؤسسة الغامدي للمقاولات",
    phone: "+966 54 789 0123",
    email: "yousef@ghamdi-contracting.sa",
    value: 430000,
    stage: "interested",
    assignee: "نورة الزهراني",
    status: "follow_up",
    notes: "طلب موعد لمراجعة شروط التمويل بشكل مفصّل.",
    updatedAt: "2026-03-06",
  },
  {
    id: "p8",
    name: "مريم الحربي",
    company: "الحربي للاستثمار والتطوير",
    phone: "+966 56 890 1234",
    email: "maryam@harbi-invest.sa",
    value: 680000,
    stage: "lead",
    assignee: "أحمد العتيبي",
    status: "hot",
    notes: "عميلة جاءت بإحالة من سلطان القحطاني.",
    updatedAt: "2026-03-05",
  },
  {
    id: "p9",
    name: "تركي المالكي",
    company: "المالكي للمواد الغذائية",
    phone: "+966 50 901 2345",
    email: "turki@maliki-food.sa",
    value: 260000,
    stage: "new",
    assignee: "سارة محمد",
    status: "warm",
    notes: "تواصل عبر الموقع الإلكتروني. ينتظر اتصالاً أولياً.",
    updatedAt: "2026-03-07",
  },
  {
    id: "p10",
    name: "دانة العجمي",
    company: "العجمي للاستشارات المالية",
    phone: "+966 55 012 3456",
    email: "dana@ajami-consulting.sa",
    value: 375000,
    stage: "interested",
    assignee: "خالد السعدي",
    status: "warm",
    notes: "ترغب في الاطلاع على التفاصيل الكاملة لبرنامج المرابحة.",
    updatedAt: "2026-03-06",
  },
];
